### ISSUE TITLE
generator strategy

### ISSUE THREAD

**Issue by rcoreilly** [goki/enums#1]
Given that we want Values and Strings, it might make sense to create those as static initialized slices and then dynamically create and cache a map from string -> value when the SetString method is first called.  

It looks like current stringer code uses a for loop for SetString, regardless of numbers of items, which is probably pretty inefficient relative to a map, so it would be better to just gen the map.

and then no need for the optimized concatenated string thing..

**Comment by rcoreilly** [comment]
actually looks like enumer generates maps in advance and the const string is probably good because it is const and not a var.. https://github.com/dmarkham/enumer/blob/master/testdata/day.golden

**Comment by kkoreilly** [comment]
Implemented everything.
