### ISSUE TITLE
Please update go.mod to only use major/minor revisions across all goki projects

### ISSUE THREAD

**Issue by ChronosMasterOfAllTime** [goki/enums#6]
I was poking around and noticed the go.mod had the version listed as `go 1.21.0`

If you update the go.mod file to be `go 1.21` instead this will stop consuming projects to have to inject toolchain compatibility in their files.

because this project hardcodes the patch version of go, we get an outcome in our projects go.mod using goki/*  after running a mod tidy like so:

```go
go 1.21.0

toolchain go1.21.4
```

I was going to put out a PR, but quickly realized all the goki projects will need update, and I figured you all would be better suited to handle this.

**Comment by kkoreilly** [comment]
Thanks for reporting this. I will fix this in the context of a project-wide release cycle, which I will do either tonight or tomorrow.

**Comment by ChronosMasterOfAllTime** [comment]
> Thanks for reporting this. I will fix this in the context of a project-wide release cycle, which I will do either tonight or tomorrow.

Thank you!

**Comment by kkoreilly** [comment]
This should now be fixed; if you run `go get -u ./...`, you should be able to remove the toolchain directive from your go mod and just have `go 1.21`, and that directive should not be generated from now on.

**Comment by ChronosMasterOfAllTime** [comment]
Verified and it is fixed now. Closing this issue 👍
